$ANSIBLE_VAULT;1.1;AES256
39633335306461636236636534306134363961303535643535386361383438336135386138643165
6461663132366363663732626464633231366162663038340a626363643836623432353435656434
64336234616130633133303162636661643761303863643937363231653834623235373736373033
3139346663343734300a326666633063636162383838643239313132333032316338303961386261
30646432613036313465666537306565626531623964323766303431623539623234633931356536
61306365326331323361326363373364336637323065616637313830383736326231316334353433
36353931313037353936383462386432323533623337616534613262353865373266613962643863
36643335393937653238653062613138383134313638616336326161666437343130626664303232
39333539366433626236393562323138346232376165643139303035323861666238393034336365
64343535333230363330353062356630393564653063633263653761353034306462303732653465
30616539613339303839393436393930333832643762663964653938346239613937346336373863
61323762663939643565
