$ANSIBLE_VAULT;1.1;AES256
65623266663663383265333733353761356561343431626131353864356632643435356466316332
3866363363383834383738323165626265333230336339640a633864393735363361363535663839
66666662313964343038316235376233326433346334353264326435623363666535383731356262
3664306532363365640a353965363533336531326464313035616664666135313431656663386333
30633061326462343633376338346331313864666663313362666234336435376661663864613134
64623331636630363566313031353865363661666532633139633966333163333661363134383736
31386136653263636530653266646437356533633961626338363337323333643936623431363665
38393666663865363234
